ARUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
BOARD_TAG = uno
USER_LIB_PATH = /home/pi/sketchbook/libraries
ARDUINO_LIBS = DHT-sensor-library Adafruit_Sensor LiquidCrystal

include /usr/share/arduino/Arduino.mk
